### ISSUE TITLE
Generate Java classes from a Bootstrap 'schema'?

### ISSUE THREAD

**Issue by emilianbold** [nielsgron/quicksilver#10]
Hello,

I wonder if it would be worth looking into generating the Java classes from a Bootstrap 'schema' (think XSD like) file?

In theory based on the .css classes we could infer how to map these properties to our Java class tree and generate code that way.

Of course, the code might be quite ugly but perhaps it can be refined afterwards? My other concern is that .css might be too low-level and we want to present some 'higher-level' view which needs manual intervention?

Anyhow, seems an interesting angle to me.

**Comment by nielsgron** [comment]
The end goal is to provide a high level API.  Not sure what the generated code would look like.
