### ISSUE TITLE
Create website via gh-pages branch

### ISSUE THREAD

**Issue by emilianbold** [nielsgron/quicksilver#34]
If you open http://emilianbold.github.io/quicksilver you should see a live demo of Quicksilver. It's actually a static crawl saved in the gh-pages branch of my repository but seems sufficient for demo purposes.

I suggest you create a `gh-pages` branch and configure GitHub Pages from https://github.com/nielsgron/quicksilver/settings .

Then I'll be able to make PRs against gh-pages too.

Maybe we should move the demo to `quicksilver/demo` and leave the main page for some actual page explaining more about the project?

**Comment by nielsgron** [comment]
I've done the following : 1) created repo quicksilver-demo, 2) create gh-pages branch in quicksilver-demo and quicksilver.
